<?php
declare(strict_types=1);

namespace Modera\SalesfrontConnector\Model\Config\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;

class EquipmentOptions extends AbstractSource
{
    /**
     * Equipment options for attribute
     */
    public const EQUIPMENT_LIST = [
        'interiorType',
        'interiorTypeLeather',
        'interiorTypePartialLeather',
        'interiorTypeAlcantara',
        'interiorTypeVelour',
        'interiorTypeFabric',
        'interiorTypeOther',
        'interiorColor',
        'interiorColorBlack',
        'interiorColorGrey',
        'interiorColorBeige',
        'interiorColorBrown',
        'interiorColorOther',
        'electricAdjustableSeats',
        'electricAdjustableSeatsDetails',
        'electricAdjustableSeatsFront',
        'electricAdjustableSeatsBack',
        'electricAdjustableSeatsMemory',
        'adjustableSeatHeight',
        'adjustableSeatHeightDriver',
        'adjustableSeatHeightPassenger',
        'electricHeatedSeats',
        'electricHeatedSeatsFront',
        'electricHeatedSeatsRear',
        'ventilatedSeats',
        'ventilatedSeatsFront',
        'ventilatedSeatsBack',
        'adjustableBackrestShape',
        'adjustableBackrestShapeDriver',
        'adjustableBackrestShapePassenger',
        'foldDownBackrest',
        'foldDownBackrestPassenger',
        'foldFlatPassengerSeat',
        'armRestFront',
        'armRestFrontCompartment',
        'armRestRear',
        'armRestRearCompartment',
        'sportSeats',
        'massageSeats',
        'comfortSeats',
        'frontSeatPockets',
        'interiorLath',
        'interiorLathWood',
        'interiorLathOther',
        'interorMats',
        'interiorMatsVelour',
        'interiorMatsTextile',
        'interiorMatsRubber',
        'drawerUnderFrontSeats',
        'cargoMat',
        'cupHolders',
        'cupHoldersFront',
        'cupHoldersRear',
        'leatherShiftLever',
        'leatherHandBrakeHandle',
        'adjustableSteering',
        'adjustableSteeringHeightDepth',
        'adjustableSteeringElectric',
        'adjustableSteeringMemory',
        'multifunctionalWheel',
        'leatherSteeringWheel',
        'heatedSteeringWheel',
        'paddleShifters',
        'racingSteeringWheel',
        'powerSteering',
        'powerSteeringSpeedPropotional',
        'centralLocking',
        'centralLockingRemote',
        'abs',
        'airbag',
        'airbagSideCurtain',
        'airbagPassengerOff',
        'ebs',
        'alarmSystem',
        'alarmTowAwayProtect',
        'alarmInteriorMotionSensor',
        'alarmTwoWayCommunication',
        'fatigueWarningSystem',
        'satelliteTrackingSystem',
        'immobilizer',
        'esp',
        'brakingForceRegulator',
        'laneDepartureWarning',
        'blindSpotMonitor',
        'trafficSignRecognition',
        'nightVisionAssist',
        'collisionAvoidance',
        'distanceWarningSystem',
        'emergencyBrakeAssist',
        'isofix',
        'isofixPassengerSeat',
        'isofixRearSeat',
        'tractionControlSystem',
        'headRestraints',
        'headRestraintsFrontSeats',
        'headRestraintsRearSeats',
        'extraBrakeLight',
        'rainSensor',
        'seatBeltPreTighteners',
        'headlightTypeBiXenon',
        'headlightTypeLaser',
        'headlightTypeXenon',
        'headlightTypeXenonLowBeam',
        'headlightTypeXenonHighBeam',
        'headlightTypeLed',
        'daytimeRunningLampsLed',
        'daytimeRunningLampsLowBeam',
        'daytimeRunningLampsHighBeam',
        'daytimeRunningLampsRear',
        'headlightWasherSystem',
        'fogLights',
        'fogLightsFront',
        'fogLightsRear',
        'fogLightsCorneringFunction',
        'headlightRangeAdjustment',
        'adaptiveLights',
        'adaptiveCorneringLights',
        'lightSensor',
        'highBeamAssist',
        'glareFreeHighBeam',
        'extraLights',
        'extraLightsDetails',
        'ambientLighting',
        'insideIlluminatedDoors',
        'spotLights',
        'comeLeaveHomeSystem',
        'airConditioner',
        'climatisationAuto',
        'climatisation2Zone',
        'climatisation3Zone',
        'climatisation4Zone',
        'climatisationRearSeats',
        'electricExteriorMirrors',
        'electricExteriorMirrorsHeated',
        'electricExteriorMirrorsFolding',
        'electricExteriorMirrorsMemory',
        'dimmingMirror',
        'dimmingMirrorInterior',
        'dimmingMirrorsExterior',
        'electricWindows',
        'electricWindowsFront',
        'electricWindowsRear',
        'tintedWindows',
        'panoramicGlassRoof',
        'sunroof',
        'sunroofGlass',
        'sunroofElectric',
        'cruiseControl',
        'cruiseControlAdaptive',
        'doorCloseAid',
        'keylessEntry',
        'electricTailgate',
        'electricTailgateGestureActivation',
        'electricTailgateRemoteControl',
        'electricSideDoors',
        'mirrorSunshields',
        'mirrorSunshieldEnlighted',
        'rearWindowBlind',
        'rearWindowBlindElectric',
        'doorCurtains',
        'doorCurtainsElectric',
        'auxHeating',
        'auxHeatingEngine',
        'auxHeatingInterior',
        'auxHeatingInteriorExtra',
        'auxHeatingDetails',
        'parkingCamera',
        'parkingCamera360',
        'parkingCameraFront',
        'automatedParking',
        'headUpDisplay',
        'parkingSensors',
        'parkingSensorsFront',
        'parkingSensorsBack',
        'stereo',
        'stereoSystemDetails',
        'factoryFittedStereo',
        'cdPlayer',
        'mp3',
        'usb',
        'auxIn',
        'memoryCard',
        'remoteControl',
        'audioExtras',
        'stereoAmplifier',
        'speakers',
        'subwoofer',
        'cdMultichanger',
        'carplay',
        'androidAuto',
        'dvd',
        'electricAntenna',
        'lcdScreen',
        'lcdScreenDetails',
        'lcdScreenFront',
        'lcdScreenRear',
        'navigationSystem',
        'navigationSystemMap',
        'navigationSystemVoiceControl',
        'onBoardComputer',
        'carPhone',
        'handsFreePhoneSystem',
        'handsFreePhoneSystemDetails',
        'radioTuner',
        'radioDab',
        'tv',
        'touchscreen',
        'bluetooth',
        'wifiHotspot',
        'integratedMusicStreaming',
        'wirelessCharging',
        'digitalCockpit',
        'summerTyres',
        'summerTyreDetails',
        'winterTyres',
        'winterTyreDetails',
        'allSeasonTyres',
        'alloyWheels',
        'alloyWheelSize',
        'alloyWheelBrand',
        'steelWheels',
        'dustShields',
        'tirePressureMonitoring',
        'adjustableSuspension',
        'adjustableSuspensionElectric',
        'adjustableSuspensionStiffness',
        'adjustableSuspensionHeight',
        'airSuspension',
        'startStop',
        'powerOutlet12V',
        'roofRails',
        'roofRailDetails',
        'doubleGlazing',
        'armoured',
        'skiBag',
        'outsideTemperatureDisplay',
        'heatedWindshield',
        'windshieldWasherDefrost',
        'rearWindowHeating',
        'rearWindowCleaner',
        'cargoBarrier',
        'cargoAttachmentHooks',
        'luggageCover',
        'luggageNet',
        'loadFloorSliding',
        'trailerCoupling',
        'trailerCouplingFixed',
        'trailerCouplingSwiveling',
        'trailerCouplingDetachable',
        'spareTyre',
        'emergencyTyre',
        'emergencyTyreRepairKit',
        'winterPackage',
        'sportPackage',
        'spoilers',
        'smokersPackage',
        'disabledAccessible',
        'taxi',
        'hillStartAssist',
        'mountainBrake',
        'voiceControl',
        'warranty',
        'serviceBook',
        'multipleKeys',
        'numberOfKeys',
        'numberOfImmobilizerRemotes',
        'numberOfAlarmRemotes',
        'differentialLock',
        'differentialLockElectronic',
        'differentialLockFront',
        'differentialLockRear',
    ];

    /**
     * @inheritDoc
     */
    public function getAllOptions(): array
    {
        if ($this->_options === null) {
            $this->_options = [
                ['value' => '1', 'label' => 'interiorType'],
                ['value' => '2', 'label' => 'interiorTypeLeather'],
                ['value' => '3', 'label' => 'interiorTypePartialLeather'],
                ['value' => '4', 'label' => 'interiorTypeAlcantara'],
                ['value' => '5', 'label' => 'interiorTypeVelour'],
                ['value' => '6', 'label' => 'interiorTypeFabric'],
                ['value' => '7', 'label' => 'interiorTypeOther'],
                ['value' => '8', 'label' => 'interiorColor'],
                ['value' => '9', 'label' => 'interiorColorBlack'],
                ['value' => '10', 'label' => 'interiorColorGrey'],
                ['value' => '11', 'label' => 'interiorColorBeige'],
                ['value' => '12', 'label' => 'interiorColorBrown'],
                ['value' => '13', 'label' => 'interiorColorOther'],
                ['value' => '14', 'label' => 'electricAdjustableSeats'],
                ['value' => '15', 'label' => 'electricAdjustableSeatsDetails'],
                ['value' => '16', 'label' => 'electricAdjustableSeatsFront'],
                ['value' => '17', 'label' => 'electricAdjustableSeatsBack'],
                ['value' => '18', 'label' => 'electricAdjustableSeatsMemory'],
                ['value' => '19', 'label' => 'adjustableSeatHeight'],
                ['value' => '20', 'label' => 'adjustableSeatHeightDriver'],
                ['value' => '21', 'label' => 'adjustableSeatHeightPassenger'],
                ['value' => '22', 'label' => 'electricHeatedSeats'],
                ['value' => '23', 'label' => 'electricHeatedSeatsFront'],
                ['value' => '24', 'label' => 'electricHeatedSeatsRear'],
                ['value' => '25', 'label' => 'ventilatedSeats'],
                ['value' => '26', 'label' => 'ventilatedSeatsFront'],
                ['value' => '27', 'label' => 'ventilatedSeatsBack'],
                ['value' => '28', 'label' => 'adjustableBackrestShape'],
                ['value' => '29', 'label' => 'adjustableBackrestShapeDriver'],
                ['value' => '30', 'label' => 'adjustableBackrestShapePassenger'],
                ['value' => '31', 'label' => 'foldDownBackrest'],
                ['value' => '32', 'label' => 'foldDownBackrestPassenger'],
                ['value' => '33', 'label' => 'foldFlatPassengerSeat'],
                ['value' => '34', 'label' => 'armRestFront'],
                ['value' => '35', 'label' => 'armRestFrontCompartment'],
                ['value' => '36', 'label' => 'armRestRear'],
                ['value' => '37', 'label' => 'armRestRearCompartment'],
                ['value' => '38', 'label' => 'sportSeats'],
                ['value' => '39', 'label' => 'massageSeats'],
                ['value' => '40', 'label' => 'comfortSeats'],
                ['value' => '41', 'label' => 'frontSeatPockets'],
                ['value' => '42', 'label' => 'interiorLath'],
                ['value' => '43', 'label' => 'interiorLathWood'],
                ['value' => '44', 'label' => 'interiorLathOther'],
                ['value' => '45', 'label' => 'interorMats'],
                ['value' => '46', 'label' => 'interiorMatsVelour'],
                ['value' => '47', 'label' => 'interiorMatsTextile'],
                ['value' => '48', 'label' => 'interiorMatsRubber'],
                ['value' => '49', 'label' => 'drawerUnderFrontSeats'],
                ['value' => '50', 'label' => 'cargoMat'],
                ['value' => '51', 'label' => 'cupHolders'],
                ['value' => '52', 'label' => 'cupHoldersFront'],
                ['value' => '53', 'label' => 'cupHoldersRear'],
                ['value' => '54', 'label' => 'leatherShiftLever'],
                ['value' => '55', 'label' => 'leatherHandBrakeHandle'],
                ['value' => '56', 'label' => 'adjustableSteering'],
                ['value' => '57', 'label' => 'adjustableSteeringHeightDepth'],
                ['value' => '58', 'label' => 'adjustableSteeringElectric'],
                ['value' => '59', 'label' => 'adjustableSteeringMemory'],
                ['value' => '60', 'label' => 'multifunctionalWheel'],
                ['value' => '61', 'label' => 'leatherSteeringWheel'],
                ['value' => '62', 'label' => 'heatedSteeringWheel'],
                ['value' => '63', 'label' => 'paddleShifters'],
                ['value' => '64', 'label' => 'racingSteeringWheel'],
                ['value' => '65', 'label' => 'powerSteering'],
                ['value' => '66', 'label' => 'powerSteeringSpeedPropotional'],
                ['value' => '67', 'label' => 'centralLocking'],
                ['value' => '68', 'label' => 'centralLockingRemote'],
                ['value' => '69', 'label' => 'abs'],
                ['value' => '70', 'label' => 'airbag'],
                ['value' => '71', 'label' => 'airbagSideCurtain'],
                ['value' => '72', 'label' => 'airbagPassengerOff'],
                ['value' => '73', 'label' => 'ebs'],
                ['value' => '74', 'label' => 'alarmSystem'],
                ['value' => '75', 'label' => 'alarmTowAwayProtect'],
                ['value' => '76', 'label' => 'alarmInteriorMotionSensor'],
                ['value' => '77', 'label' => 'alarmTwoWayCommunication'],
                ['value' => '78', 'label' => 'fatigueWarningSystem'],
                ['value' => '79', 'label' => 'satelliteTrackingSystem'],
                ['value' => '80', 'label' => 'immobilizer'],
                ['value' => '81', 'label' => 'esp'],
                ['value' => '82', 'label' => 'brakingForceRegulator'],
                ['value' => '83', 'label' => 'laneDepartureWarning'],
                ['value' => '84', 'label' => 'blindSpotMonitor'],
                ['value' => '85', 'label' => 'trafficSignRecognition'],
                ['value' => '86', 'label' => 'nightVisionAssist'],
                ['value' => '87', 'label' => 'collisionAvoidance'],
                ['value' => '88', 'label' => 'distanceWarningSystem'],
                ['value' => '89', 'label' => 'emergencyBrakeAssist'],
                ['value' => '90', 'label' => 'isofix'],
                ['value' => '91', 'label' => 'isofixPassengerSeat'],
                ['value' => '92', 'label' => 'isofixRearSeat'],
                ['value' => '93', 'label' => 'tractionControlSystem'],
                ['value' => '94', 'label' => 'headRestraints'],
                ['value' => '95', 'label' => 'headRestraintsFrontSeats'],
                ['value' => '96', 'label' => 'headRestraintsRearSeats'],
                ['value' => '97', 'label' => 'extraBrakeLight'],
                ['value' => '98', 'label' => 'rainSensor'],
                ['value' => '99', 'label' => 'seatBeltPreTighteners'],
                ['value' => '100', 'label' => 'headlightTypeBiXenon'],
                ['value' => '101', 'label' => 'headlightTypeLaser'],
                ['value' => '102', 'label' => 'headlightTypeXenon'],
                ['value' => '103', 'label' => 'headlightTypeXenonLowBeam'],
                ['value' => '104', 'label' => 'headlightTypeXenonHighBeam'],
                ['value' => '105', 'label' => 'headlightTypeLed'],
                ['value' => '106', 'label' => 'daytimeRunningLampsLed'],
                ['value' => '107', 'label' => 'daytimeRunningLampsLowBeam'],
                ['value' => '108', 'label' => 'daytimeRunningLampsHighBeam'],
                ['value' => '109', 'label' => 'daytimeRunningLampsRear'],
                ['value' => '110', 'label' => 'headlightWasherSystem'],
                ['value' => '111', 'label' => 'fogLights'],
                ['value' => '112', 'label' => 'fogLightsFront'],
                ['value' => '113', 'label' => 'fogLightsRear'],
                ['value' => '114', 'label' => 'fogLightsCorneringFunction'],
                ['value' => '115', 'label' => 'headlightRangeAdjustment'],
                ['value' => '116', 'label' => 'adaptiveLights'],
                ['value' => '117', 'label' => 'adaptiveCorneringLights'],
                ['value' => '118', 'label' => 'lightSensor'],
                ['value' => '119', 'label' => 'highBeamAssist'],
                ['value' => '120', 'label' => 'glareFreeHighBeam'],
                ['value' => '121', 'label' => 'extraLights'],
                ['value' => '122', 'label' => 'extraLightsDetails'],
                ['value' => '123', 'label' => 'ambientLighting'],
                ['value' => '124', 'label' => 'insideIlluminatedDoors'],
                ['value' => '125', 'label' => 'spotLights'],
                ['value' => '126', 'label' => 'comeLeaveHomeSystem'],
                ['value' => '127', 'label' => 'airConditioner'],
                ['value' => '128', 'label' => 'climatisationAuto'],
                ['value' => '129', 'label' => 'climatisation2Zone'],
                ['value' => '130', 'label' => 'climatisation3Zone'],
                ['value' => '131', 'label' => 'climatisation4Zone'],
                ['value' => '132', 'label' => 'climatisationRearSeats'],
                ['value' => '133', 'label' => 'electricExteriorMirrors'],
                ['value' => '134', 'label' => 'electricExteriorMirrorsHeated'],
                ['value' => '135', 'label' => 'electricExteriorMirrorsFolding'],
                ['value' => '136', 'label' => 'electricExteriorMirrorsMemory'],
                ['value' => '137', 'label' => 'dimmingMirror'],
                ['value' => '138', 'label' => 'dimmingMirrorInterior'],
                ['value' => '139', 'label' => 'dimmingMirrorsExterior'],
                ['value' => '140', 'label' => 'electricWindows'],
                ['value' => '141', 'label' => 'electricWindowsFront'],
                ['value' => '142', 'label' => 'electricWindowsRear'],
                ['value' => '143', 'label' => 'tintedWindows'],
                ['value' => '144', 'label' => 'panoramicGlassRoof'],
                ['value' => '145', 'label' => 'sunroof'],
                ['value' => '146', 'label' => 'sunroofGlass'],
                ['value' => '147', 'label' => 'sunroofElectric'],
                ['value' => '148', 'label' => 'cruiseControl'],
                ['value' => '149', 'label' => 'cruiseControlAdaptive'],
                ['value' => '150', 'label' => 'doorCloseAid'],
                ['value' => '151', 'label' => 'keylessEntry'],
                ['value' => '152', 'label' => 'electricTailgate'],
                ['value' => '153', 'label' => 'electricTailgateGestureActivation'],
                ['value' => '154', 'label' => 'electricTailgateRemoteControl'],
                ['value' => '155', 'label' => 'electricSideDoors'],
                ['value' => '156', 'label' => 'mirrorSunshields'],
                ['value' => '157', 'label' => 'mirrorSunshieldEnlighted'],
                ['value' => '158', 'label' => 'rearWindowBlind'],
                ['value' => '159', 'label' => 'rearWindowBlindElectric'],
                ['value' => '160', 'label' => 'doorCurtains'],
                ['value' => '161', 'label' => 'doorCurtainsElectric'],
                ['value' => '162', 'label' => 'auxHeating'],
                ['value' => '163', 'label' => 'auxHeatingEngine'],
                ['value' => '164', 'label' => 'auxHeatingInterior'],
                ['value' => '165', 'label' => 'auxHeatingInteriorExtra'],
                ['value' => '166', 'label' => 'auxHeatingDetails'],
                ['value' => '167', 'label' => 'parkingCamera'],
                ['value' => '168', 'label' => 'parkingCamera360'],
                ['value' => '169', 'label' => 'parkingCameraFront'],
                ['value' => '170', 'label' => 'automatedParking'],
                ['value' => '171', 'label' => 'headUpDisplay'],
                ['value' => '172', 'label' => 'parkingSensors'],
                ['value' => '173', 'label' => 'parkingSensorsFront'],
                ['value' => '174', 'label' => 'parkingSensorsBack'],
                ['value' => '175', 'label' => 'stereo'],
                ['value' => '176', 'label' => 'stereoSystemDetails'],
                ['value' => '177', 'label' => 'factoryFittedStereo'],
                ['value' => '178', 'label' => 'cdPlayer'],
                ['value' => '179', 'label' => 'mp3'],
                ['value' => '180', 'label' => 'usb'],
                ['value' => '181', 'label' => 'auxIn'],
                ['value' => '182', 'label' => 'memoryCard'],
                ['value' => '183', 'label' => 'remoteControl'],
                ['value' => '184', 'label' => 'audioExtras'],
                ['value' => '185', 'label' => 'stereoAmplifier'],
                ['value' => '186', 'label' => 'speakers'],
                ['value' => '187', 'label' => 'subwoofer'],
                ['value' => '188', 'label' => 'cdMultichanger'],
                ['value' => '189', 'label' => 'carplay'],
                ['value' => '190', 'label' => 'androidAuto'],
                ['value' => '191', 'label' => 'dvd'],
                ['value' => '192', 'label' => 'electricAntenna'],
                ['value' => '193', 'label' => 'lcdScreen'],
                ['value' => '194', 'label' => 'lcdScreenDetails'],
                ['value' => '195', 'label' => 'lcdScreenFront'],
                ['value' => '196', 'label' => 'lcdScreenRear'],
                ['value' => '197', 'label' => 'navigationSystem'],
                ['value' => '198', 'label' => 'navigationSystemMap'],
                ['value' => '199', 'label' => 'navigationSystemVoiceControl'],
                ['value' => '200', 'label' => 'onBoardComputer'],
                ['value' => '201', 'label' => 'carPhone'],
                ['value' => '202', 'label' => 'handsFreePhoneSystem'],
                ['value' => '203', 'label' => 'handsFreePhoneSystemDetails'],
                ['value' => '204', 'label' => 'radioTuner'],
                ['value' => '205', 'label' => 'radioDab'],
                ['value' => '206', 'label' => 'tv'],
                ['value' => '207', 'label' => 'touchscreen'],
                ['value' => '208', 'label' => 'bluetooth'],
                ['value' => '209', 'label' => 'wifiHotspot'],
                ['value' => '210', 'label' => 'integratedMusicStreaming'],
                ['value' => '211', 'label' => 'wirelessCharging'],
                ['value' => '212', 'label' => 'digitalCockpit'],
                ['value' => '213', 'label' => 'summerTyres'],
                ['value' => '214', 'label' => 'summerTyreDetails'],
                ['value' => '215', 'label' => 'winterTyres'],
                ['value' => '216', 'label' => 'winterTyreDetails'],
                ['value' => '217', 'label' => 'allSeasonTyres'],
                ['value' => '218', 'label' => 'alloyWheels'],
                ['value' => '219', 'label' => 'alloyWheelSize'],
                ['value' => '220', 'label' => 'alloyWheelBrand'],
                ['value' => '221', 'label' => 'steelWheels'],
                ['value' => '222', 'label' => 'dustShields'],
                ['value' => '223', 'label' => 'tirePressureMonitoring'],
                ['value' => '224', 'label' => 'adjustableSuspension'],
                ['value' => '225', 'label' => 'adjustableSuspensionElectric'],
                ['value' => '226', 'label' => 'adjustableSuspensionStiffness'],
                ['value' => '227', 'label' => 'adjustableSuspensionHeight'],
                ['value' => '228', 'label' => 'airSuspension'],
                ['value' => '229', 'label' => 'startStop'],
                ['value' => '230', 'label' => 'powerOutlet12V'],
                ['value' => '231', 'label' => 'roofRails'],
                ['value' => '232', 'label' => 'roofRailDetails'],
                ['value' => '233', 'label' => 'doubleGlazing'],
                ['value' => '234', 'label' => 'armoured'],
                ['value' => '235', 'label' => 'skiBag'],
                ['value' => '236', 'label' => 'outsideTemperatureDisplay'],
                ['value' => '237', 'label' => 'heatedWindshield'],
                ['value' => '238', 'label' => 'windshieldWasherDefrost'],
                ['value' => '239', 'label' => 'rearWindowHeating'],
                ['value' => '240', 'label' => 'rearWindowCleaner'],
                ['value' => '241', 'label' => 'cargoBarrier'],
                ['value' => '242', 'label' => 'cargoAttachmentHooks'],
                ['value' => '243', 'label' => 'luggageCover'],
                ['value' => '244', 'label' => 'luggageNet'],
                ['value' => '245', 'label' => 'loadFloorSliding'],
                ['value' => '246', 'label' => 'trailerCoupling'],
                ['value' => '247', 'label' => 'trailerCouplingFixed'],
                ['value' => '248', 'label' => 'trailerCouplingSwiveling'],
                ['value' => '249', 'label' => 'trailerCouplingDetachable'],
                ['value' => '250', 'label' => 'spareTyre'],
                ['value' => '251', 'label' => 'emergencyTyre'],
                ['value' => '252', 'label' => 'emergencyTyreRepairKit'],
                ['value' => '253', 'label' => 'winterPackage'],
                ['value' => '254', 'label' => 'sportPackage'],
                ['value' => '255', 'label' => 'spoilers'],
                ['value' => '256', 'label' => 'smokersPackage'],
                ['value' => '257', 'label' => 'disabledAccessible'],
                ['value' => '258', 'label' => 'taxi'],
                ['value' => '259', 'label' => 'hillStartAssist'],
                ['value' => '260', 'label' => 'mountainBrake'],
                ['value' => '261', 'label' => 'voiceControl'],
                ['value' => '262', 'label' => 'warranty'],
                ['value' => '263', 'label' => 'serviceBook'],
                ['value' => '264', 'label' => 'multipleKeys'],
                ['value' => '265', 'label' => 'numberOfKeys'],
                ['value' => '266', 'label' => 'numberOfImmobilizerRemotes'],
                ['value' => '267', 'label' => 'numberOfAlarmRemotes'],
                ['value' => '268', 'label' => 'differentialLock'],
                ['value' => '269', 'label' => 'differentialLockElectronic'],
                ['value' => '270', 'label' => 'differentialLockFront'],
                ['value' => '271', 'label' => 'differentialLockRear'],
            ];
        }

        return $this->_options;
    }

    /**
     * Get text of the option value
     *
     * @param string|integer $value
     * @return string|bool
     */
    public function getOptionValue($value)
    {
        foreach ($this->getAllOptions() as $option) {
            if ($option['value'] == $value) {
                return $option['label'];
            }
        }

        return false;
    }
}
